# Generated by Django 3.2.20 on 2023-08-01 12:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Freedom and Thrive', 'Freedom and Thrive'), ('Ignite Your Potential', 'Ignite Your Potential'), ('Unleash Your Extraordinary Life', 'Unleash Your Extraordinary Life'), ('Breakthrough to Freedom', 'Breakthrough to Freedom')], default='', max_length=200)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=3600))),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
